/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab11.pkg1;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author localuser
 */
public class BigBang extends javax.swing.JFrame {

    private int rock = 1;
    private int paper = 2;
    private int scissor = 3;
    private int lizard = 4;
    private int spock = 5;
    private int choice = 0;
    private int n = 0;
    private int playerScore = 0;
    private int compScore = 0;
    public boolean win = false;

    /**
     * Creates new form BigBang
     */
    public BigBang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpButton = new javax.swing.ButtonGroup();
        panelGame = new javax.swing.JPanel();
        lblChoice = new javax.swing.JLabel();
        btnRock = new javax.swing.JRadioButton();
        btnPaper = new javax.swing.JRadioButton();
        btnScissor = new javax.swing.JRadioButton();
        btnLizard = new javax.swing.JRadioButton();
        btnSpock = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        lblPlayer = new javax.swing.JLabel();
        lblComp = new javax.swing.JLabel();
        txtPlayerScore = new javax.swing.JTextField();
        txtCompScore = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChoice.setText("Your choice:");

        grpButton.add(btnRock);
        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        grpButton.add(btnPaper);
        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        grpButton.add(btnScissor);
        btnScissor.setText("Scissors");
        btnScissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorActionPerformed(evt);
            }
        });

        grpButton.add(btnLizard);
        btnLizard.setText("Lizard");
        btnLizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLizardActionPerformed(evt);
            }
        });

        grpButton.add(btnSpock);
        btnSpock.setText("Spock");
        btnSpock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpockActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        lblPlayer.setText("Player Score:");

        lblComp.setText("Computer Score:");

        txtPlayerScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerScoreActionPerformed(evt);
            }
        });

        btnStart.setText("GAME START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSpock)
                            .addComponent(btnLizard)
                            .addComponent(btnScissor)
                            .addComponent(btnPaper)
                            .addComponent(btnRock)
                            .addComponent(lblChoice))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer)
                            .addComponent(lblComp))
                        .addGap(33, 33, 33)
                        .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlayerScore)
                            .addComponent(txtCompScore)))
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnStart)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addComponent(lblChoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnScissor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLizard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpock)))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addGap(3, 3, 3)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblComp)
                    .addComponent(txtCompScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorActionPerformed
        choice = 3;// TODO add your handling code here:
    }//GEN-LAST:event_btnScissorActionPerformed

    private void txtPlayerScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerScoreActionPerformed

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        choice = 1;// TODO add your handling code here:
    }//GEN-LAST:event_btnRockActionPerformed

    private void btnLizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLizardActionPerformed
        choice = 4;// TODO add your handling code here:
    }//GEN-LAST:event_btnLizardActionPerformed

    private void btnSpockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpockActionPerformed
        choice = 5;// TODO add your handling code here:
    }//GEN-LAST:event_btnSpockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        choice = 2;// TODO add your handling code here:
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Random rand = new Random();
        n = rand.nextInt(5) + 1;
        play();
        txtResult.setText("Results: \n"
                + "PLAYER CHOSE " + choice(choice)
                + " \nCOMPUTER CHOSE " + choice(n) + "\n" + WinorLose(win));
        if (win) {
            scorePlayer();
            txtPlayerScore.setText(Integer.toString(playerScore));
        } else {
            scoreComp();
            txtCompScore.setText(Integer.toString(compScore));
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed
    private String WinorLose(boolean win) {
        String s = "";
        if (win) {
            s = String.format("YOU WIN THIS ROUND");
        } else {
            s = String.format("YOU LOSE THIS ROUND");
        }
        return s;
    }

    private void play() {
        if (choice == 1) {
            if (n == 3 || n == 4) {
                // scorePlayer();
                win = true;
            }
            if (n == 2 || n == 5) {
                // scoreComp();
                win = false;
            }
            if (n == 3) {
            }
        }
        if (choice == 2) {
            if (n == 1 || n == 5) {
                // scorePlayer();
                win = true;
            }
            if (n == 4 || n == 3) {
                //scoreComp();
                win = false;
            }
            if (n == 2) {
            }
        }
        if (choice == 3) {
            if (n == 2 || n == 4) {
                // scorePlayer();
                win = true;
            }
            if (n == 1 || n == 5) {
                // scoreComp();
                win = false;
            }
            if (n == 3) {
            }
        }
        if (choice == 4) {
            if (n == 2 || n == 5) {
                // scorePlayer();
                win = true;
            }
            if (n == 1 || n == 3) {
                // scoreComp();
                win = false;
            }
            if (n == 4) {
            }
        }
        if (choice == 5) {
            if (n == 1 || n == 3) {
                // scorePlayer();
                win = true;
            }
            if (n == 2 || n == 4) {
                // scoreComp();
                win = false;
            }
            if (n == 5) {
            }
        }
    }

    private void scorePlayer() {
        ++playerScore;
        if (playerScore >= 5 || compScore >= 5) {
            gameOver();
        }
    }

    private void scoreComp() {
        ++compScore;
        if (playerScore >= 5 || compScore >= 5) {
            gameOver();
        }
    }

    private void gameOver() {
        if (playerScore > compScore) {
            int rep = JOptionPane.showConfirmDialog(this, "Your score is " + playerScore + "\n PLAYER WIN\n WOULD YOU LIKE TO RESTART?", "GAME OVER", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION){
                restart();
            }
            else{
                System.exit(0);
            }
        } else {
            int rep = JOptionPane.showConfirmDialog(this, "Your score is " + playerScore + "\n PLAYER WIN\n WOULD YOU LIKE TO RESTART?", "GAME OVER", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION){
                restart();
            }
            else{
                System.exit(0);
        }
    }}

    private String choice(int choice) {
        String s = "";
        if (choice == 1) {
            s = "ROCK";
        }
        if (choice == 2) {
            s = "PAPER";
        }
        if (choice == 3) {
            s = "SCISSOR";
        }
        if (choice == 4) {
            s = "LIZARD";
        }
        if (choice == 5) {
            s = "SPOCK";
        }

        return s;
    }
    public void setup(){
    choice = 0;
    n = 0;
    playerScore = 0;
    compScore = 0;
    win = false;
    }
    
    public void restart(){
    setup();
    new BigBang().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigBang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigBang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigBang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigBang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigBang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnLizard;
    private javax.swing.JRadioButton btnPaper;
    private javax.swing.JRadioButton btnRock;
    private javax.swing.JRadioButton btnScissor;
    private javax.swing.JRadioButton btnSpock;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup grpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblComp;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JPanel panelGame;
    private javax.swing.JTextField txtCompScore;
    private javax.swing.JTextField txtPlayerScore;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
