/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab11;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author chromalix
 */
public class Game extends javax.swing.JFrame {

    private int choice = 0;
    private int n = 0;
    private int playerScore = 0;
    private int compScore = 0;
    public boolean win = false;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChoice = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRock = new javax.swing.JRadioButton();
        btnPaper = new javax.swing.JRadioButton();
        btnScissor = new javax.swing.JRadioButton();
        btnLizzard = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPlayerScore = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCompScore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("YOUR CHOICE:");

        groupChoice.add(btnRock);
        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        groupChoice.add(btnPaper);
        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        groupChoice.add(btnScissor);
        btnScissor.setText("Scissor");
        btnScissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorActionPerformed(evt);
            }
        });

        groupChoice.add(btnLizzard);
        btnLizzard.setText("Lizard");
        btnLizzard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLizzardActionPerformed(evt);
            }
        });

        groupChoice.add(jRadioButton5);
        jRadioButton5.setText("Spock");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btnStart.setText("RockPaperScissorsLizardSpock!");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel2.setText("Player Score:");

        jLabel3.setText("Computer Score:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(btnLizzard)
                    .addComponent(btnScissor)
                    .addComponent(jLabel1)
                    .addComponent(btnRock)
                    .addComponent(btnPaper)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtCompScore)
                    .addComponent(txtPlayerScore))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnScissor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLizzard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCompScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLizzardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLizzardActionPerformed
        choice = 4; // TODO add your handling code here:
    }//GEN-LAST:event_btnLizzardActionPerformed

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        choice = 1; // TODO add your handling code here:
    }//GEN-LAST:event_btnRockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        choice = 2; // TODO add your handling code here:
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorActionPerformed
        choice = 3; // TODO add your handling code here:
    }//GEN-LAST:event_btnScissorActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        choice = 5; // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Random rand = new Random();
        n = rand.nextInt(5) + 1;
        play();
        txtResult.setText("Results: \n"
                + "PLAYER CHOSE " + choice(choice)
                + " \nCOMPUTER CHOSE " + choice(n) + "\n" + WinorLose(win));
        if (win) {
            scorePlayer();
            txtPlayerScore.setText(Integer.toString(playerScore));
        } else {
            scoreComp();
            txtCompScore.setText(Integer.toString(compScore));
        }// TODO add your handling code here:
    }                                        

    private String WinorLose(boolean win) {
        @SuppressWarnings("UnusedAssignment")
        String s = "";
        if (win) {
            s = String.format("YOU WIN THIS ROUND");
        } else {
            s = String.format("YOU LOSE THIS ROUND");
        }
        return s;
// TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void play() {
        if (choice == 1) {
            if (n == 3 || n == 4) {
                // scorePlayer();
                win = true;
            }
            if (n == 2 || n == 5) {
                // scoreComp();
                win = false;
            }
            if (n == 3) {
            }
        }
        if (choice == 2) {
            if (n == 1 || n == 5) {
                // scorePlayer();
                win = true;
            }
            if (n == 4 || n == 3) {
                //scoreComp();
                win = false;
            }
            if (n == 2) {
            }
        }
        if (choice == 3) {
            if (n == 2 || n == 4) {
                // scorePlayer();
                win = true;
            }
            if (n == 1 || n == 5) {
                // scoreComp();
                win = false;
            }
            if (n == 3) {
            }
        }
        if (choice == 4) {
            if (n == 2 || n == 5) {
                // scorePlayer();
                win = true;
            }
            if (n == 1 || n == 3) {
                // scoreComp();
                win = false;
            }
            if (n == 4) {
            }
        }
        if (choice == 5) {
            if (n == 1 || n == 3) {
                // scorePlayer();
                win = true;
            }
            if (n == 2 || n == 4) {
                // scoreComp();
                win = false;
            }
            if (n == 5) {
            }
        }
    }

    private void scorePlayer() {
        ++playerScore;
        if (playerScore >= 5 || compScore >= 5) {
            gameOver();
        }
    }

    private void scoreComp() {
        ++compScore;
        if (playerScore >= 5 || compScore >= 5) {
            gameOver();
        }
    }

    private void gameOver() {
        if (playerScore > compScore) {
            int rep = JOptionPane.showConfirmDialog(this, "Your score is " + playerScore + "\n PLAYER WIN\n WOULD YOU LIKE TO RESTART?", "GAME OVER", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {
                restart();
            } else {
                System.exit(0);
            }
        } else {
            int rep = JOptionPane.showConfirmDialog(this, "Your score is " + playerScore + "\n COMPUTER WIN\n WOULD YOU LIKE TO RESTART?", "GAME OVER", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {
                restart();
            } else {
                System.exit(0);
            }
        }
    }

    private String choice(int choice) {
        String s = "";
        if (choice == 1) {
            s = "ROCK";
        }
        if (choice == 2) {
            s = "PAPER";
        }
        if (choice == 3) {
            s = "SCISSOR";
        }
        if (choice == 4) {
            s = "LIZARD";
        }
        if (choice == 5) {
            s = "SPOCK";
        }

        return s;
    }

    public void setup() {
        choice = 0;
        n = 0;
        playerScore = 0;
        compScore = 0;
        win = false;
    }

    public void restart() {
        setup();
        new Game().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnLizzard;
    private javax.swing.JRadioButton btnPaper;
    private javax.swing.JRadioButton btnRock;
    private javax.swing.JRadioButton btnScissor;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup groupChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCompScore;
    private javax.swing.JTextField txtPlayerScore;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
